### PR TITLE
Add Cabana version

### LINKED ISSUE #32: Cabana version of n2p2
We have modified a portion of the n2p2 code to work with our library, Cabana, and proxy application, CabanaMD ((https://github.com/ECP-copa/CabanaMD). Cabana (https://github.com/ECP-copa/Cabana) is a particle library built on Kokkos (https://github.com/kokkos/kokkos/) for performance portability

@singraber has suggested we move it to this repository and I completely agree

Here is my initial plan:
- [x] Complete existing work for better interface to the n2p2 kernels that require Cabana data structures (ECP-copa/CabanaMD#37)
- [x] Move code to this repository, within `src/libnnpif-cabana` initially (see below)
- [x] Create child classes (e.g. `ModeCabana`) and override functions as necessary (there are currently implementations for `Mode`, `Element`, `CutoffFunction`)
- [x] Simplify existing setup code by calling base methods and copying to Kokkos/Cabana data structures
- [x] Add optional Kokkos/Cabana dependencies
- [x] Add documentation on building and running with Kokkos/Cabana
- [x] Remove from current repository (`master` and `OnNode` branch) 

Thank you,

### PR DESCRIPTION
**Pull request by streeve**
This adds capabilities discussed in #32. I have marked what I believe has been taken care of already. 

I have gotten this working locally together with ECP-CoPA/CabanaMD#61, which will not pass tests or be merged until this PR is done. I use `make libnnpif-cabana` and then build CabanaMD with `-DCabanaMD_ENABLE_NNP=ON`. There are no added dependencies since I currently only build the library, and do the rest in CabanaMD.

To give a bit more information about this changeset, I added the original version working with Cabana in the first commit. Because that was entirely separate from the n2p2 repo, there was duplicated functionality no longer needed (`CutoffFunction` removed) and, with inheritance from the base `Element` and `Mode`, many `setup*` functions were removed, overridden, or replaced with Kokkos/Cabana versions. The rest of the commits attempt to clean up the code and match the style of n2p2. 

Closes #32

### CODE REVIEW

**Comment by streeve** [comment]
@singraber Thanks for your help with this, let me know about changes. 

@saakethdesai @sslattery @junghans Here is the new PR to replace what is in CabanaMD

**Comment by singraber** [comment]
Thanks for all your efforts and sorry about the delay... I will work on this starting next week.

**Comment by streeve** [comment]
This should now be up to date with the CabanaMD fixes. I am not sure if I am updating the `version.h` as you intend though.

**Comment by streeve** [comment]
Thanks for updating the build/interface. It works with ECP-copa/CabanaMD#61, let me know if there are changes needed for style or capability.

**Comment by singraber** [comment]
Great, thanks for checking.. I will add some documentation before merging this with the master in the next couple of days.

**Comment by streeve** [comment]
Thank you - here's a start similar to what you have for the LAMMPS interface: 

CabanaMD interface
===============

Purpose
--------

The CabanaMD interface adds the neural network potential method in a proxy application which uses the Cabana particle library. `Cabana <https://github.com/ECP-copa/Cabana>`_ uses the Kokkos programming model to run on multi-core CPUs and GPUs; `CabanaMD <https://github.com/ECP-copa/CabanaMD>`_ provides a simple MD code to explore performance with Cabana and Kokkos. The Cabana version of n2p2 reimplements a small part of the neural network potential to enable simulations on the GPU.

Build instructions
-----------------
.. code-block:: none
   cd src
   make libnnpif INTERFACES=CabanaMD

For dynamic linking add the argument ``MODE=shared``.

.. note::
   If dynamic linking (\ ``make libnnpif MODE=shared``\ ) is used, you need to make the NNP
   libraries visibile in your system, e.g. add this line in your ``.bashrc``\ :
.. code-block:: none
   export LD_LIBRARY_PATH=<path-to-n2p2>/lib:${LD_LIBRARY_PATH}

Usage
-----
See `here <https://github.com/ECP-copa/CabanaMD/wiki>`_ for building and running CabanaMD after building n2p2 (with the CabanaMD interface).

**Comment by streeve** [comment]
Hey @singraber, any changes needed for this PR?

**Comment by singraber** [comment]
Sorry, so many things are going on at the moment.. Thanks for the documentation snippet, I will finalize this PR tomorrow. Btw, which names should I add to the list of contributors?

**Comment by streeve** [comment]
No problem, that's how things go.

Saaketh Desai and Sam Reeve

**Review by singraber — APPROVED** [review]

**Pull request merged**
